### PR TITLE
Improve password entry button and profile picture

### LINKED ISSUE #14: Improve Password Entry Button
Need to fix inconsistencies in password entry button spacing and drop-shadow:

image

* Need to move password entry button further away from prompt.
* Need to add drop shadow to button.

### PR DESCRIPTION
**Pull request by pedrosilva17**
Closes #14 
Here's how it looks:

image

### CODE REVIEW

**Comment by pedrosilva17** [comment]
Accidentally included changes from the closed pull request above.

**Comment by pedrosilva17** [comment]
I changed the shadow color as well because when applying it on the power button in the footer (which was also missing its shadow from the original XP login screen), I realized it was a fixed color brighter than the footer's background, which made it look strange. I changed it to a darker tone of blue and added 60% transparency using rgba. Now it looks good both on the footer and on the brighter background.

password button

power button

**Comment by mshernandez5** [comment]
Thanks for this! Been taking a break from most code outside of work so I appreciate the fixes.
Looks good, and never thought to try a non-rectangular picture so that is a good catch also.

**Comment by pedrosilva17** [comment]
Glad to help! This greeter is very well done and it gave me the idea of creating my own in the future. Until then, this will definitely be my laptop's login screen. And thank you for the quick reply 👍

**Pull request merged**
